-- Insert initial product catalog data
INSERT INTO products (categoria, subcategoria, item, proveedor, costo) VALUES
-- COCINA
('Cocina', 'Puertas', 'Puerta 2 Bisagras Ultramate', 'Imacasa', 109.30),
('Cocina', 'Puertas', 'Puerta 3 Bisagras Ultramate', 'Imacasa', 122.48),
('Cocina', 'Puertas', 'Puerta 2 Bisagras Luxe', 'Aglomerados', 124.87),
('Cocina', 'Puertas', 'Puerta 3 Bisagras Luxe', 'Aglomerados', 137.97),
('Cocina', 'Puertas', 'Puerta 2 Bisagras Rh', 'Aglomerados', 130.92),
('Cocina', 'Puertas', 'Puerta 3 Bisagras Rh', 'Aglomerados', 144.02),
('Cocina', 'Puertas', 'Puerta 4 Bisagras Luxe', 'Aglomerados', 160.70),
('Cocina', 'Puertas', 'Puerta 4 Bisagras Rh', 'Aglomerados', 166.75),
('Cocina', 'Cajones', 'Cajon Sencillo 40cm', 'Imacasa', 60.78),
('Cocina', 'Cajones', 'Cajon Sencillo 50cm', 'Imacasa', 67.44),
('Cocina', 'Cajones', 'Cajon Sencillo 60cm', 'Imacasa', 74.21),
('Cocina', 'Cajones', 'Cajon Sencillo 70cm', 'Imacasa', 80.98),
('Cocina', 'Cajones', 'Cajon Sencillo 80cm', 'Imacasa', 93.63),
('Cocina', 'Cajones', 'Cajon Sencillo 90cm', 'Imacasa', 99.73),
('Cocina', 'Cajones', 'Cajon Sencillo 100cm', 'Imacasa', 105.72),
('Cocina', 'Cajones', 'Cajon Tandem 40cm', 'Imacasa', 105.08),
('Cocina', 'Cajones', 'Cajon Tandem 50cm', 'Imacasa', 116.44),
('Cocina', 'Cajones', 'Cajon Tandem 60cm', 'Imacasa', 126.02),
('Cocina', 'Cajones', 'Cajon Tandem 70cm', 'Imacasa', 136.45),
('Cocina', 'Cajones', 'Cajon Tandem 80cm', 'Imacasa', 157.45),
('Cocina', 'Cajones', 'Cajon Tandem 90cm', 'Imacasa', 167.99),
('Cocina', 'Cajones', 'Cajon Tandem 100cm', 'Imacasa', 177.68),
('Cocina', 'Otros', 'Jaladera Barra 128mm', 'China', 2.50),
('Cocina', 'Otros', 'Jaladera Barra 160mm', 'China', 2.75),
('Cocina', 'Otros', 'Jaladera Barra 192mm', 'China', 3.00),
('Cocina', 'Otros', 'Jaladera Barra 320mm', 'China', 4.05),
('Cocina', 'Otros', 'Jaladera Barra 480mm', 'China', 5.15),
('Cocina', 'Otros', 'Jaladera Copla 128mm', 'China', 4.05),
('Cocina', 'Otros', 'Jaladera Ovalada', 'China', 6.00),
('Cocina', 'Otros', 'Jaladera Uña', 'China', 3.00),
('Cocina', 'Tableros', 'Tablero Aglomerado 18mm', 'Imacasa', 24.76),
('Cocina', 'Tableros', 'Tablero MDF 18mm', 'Novopan', 28.26),
('Cocina', 'Tableros', 'Contra Imacasa', 'Imacasa', 12.60),
('Cocina', 'Tableros', 'Contra Novopan', 'Novopan', 11.05),
('Cocina', 'Tableros', 'Canto 22mm', 'Imacasa', 0.35),
('Cocina', 'Muebles', 'Mueble Base 2 Puertas', 'Fabricación', 142.00),
('Cocina', 'Muebles', 'Mueble Base Cajon+Puerta', 'Fabricación', 148.00),
('Cocina', 'Muebles', 'Mueble Base 3 Cajones', 'Fabricación', 153.00),
('Cocina', 'Muebles', 'Mueble Base 4 Cajones', 'Fabricación', 157.00),
('Cocina', 'Muebles', 'Mueble Aereo 2 Puertas', 'Fabricación', 118.00),
('Cocina', 'Instalación', 'Instalación Mueble Base', 'Mano de Obra', 40.00),
('Cocina', 'Instalación', 'Instalación Mueble Aéreo', 'Mano de Obra', 30.00),

-- CLOSET
('Closet', 'Puertas', 'Puerta Corrediza 1 Hoja', 'Imacasa', 95.00),
('Closet', 'Puertas', 'Puerta Corrediza 2 Hojas', 'Imacasa', 180.00),
('Closet', 'Puertas', 'Puerta Corrediza 3 Hojas', 'Imacasa', 265.00),
('Closet', 'Puertas', 'Puerta Abatible Ultramate', 'Imacasa', 109.30),
('Closet', 'Puertas', 'Puerta Abatible Luxe', 'Aglomerados', 124.87),
('Closet', 'Cajones', 'Cajon Sencillo 40cm', 'Imacasa', 60.78),
('Closet', 'Cajones', 'Cajon Sencillo 50cm', 'Imacasa', 67.44),
('Closet', 'Cajones', 'Cajon Sencillo 60cm', 'Imacasa', 74.21),
('Closet', 'Cajones', 'Cajon Sencillo 80cm', 'Imacasa', 93.63),
('Closet', 'Cajones', 'Cajonera 3 Cajones', 'Fabricación', 165.00),
('Closet', 'Cajones', 'Cajonera 4 Cajones', 'Fabricación', 190.00),
('Closet', 'Accesorios', 'Tubo Cromado 0.90m', 'Ferretería', 8.50),
('Closet', 'Accesorios', 'Tubo Cromado 1.20m', 'Ferretería', 10.50),
('Closet', 'Accesorios', 'Soporte Tubo Cromado', 'Ferretería', 2.00),
('Closet', 'Accesorios', 'Zapatero Extraible 60cm', 'China', 45.00),
('Closet', 'Accesorios', 'Zapatero Extraible 80cm', 'China', 52.00),
('Closet', 'Accesorios', 'Corbatero Extraible', 'China', 38.00),
('Closet', 'Accesorios', 'Pantalonero Extraible', 'China', 42.00),
('Closet', 'Tableros', 'Tablero Aglomerado 18mm', 'Imacasa', 24.76),
('Closet', 'Tableros', 'Tablero MDF 18mm', 'Novopan', 28.26),
('Closet', 'Tableros', 'Canto 22mm', 'Imacasa', 0.35),
('Closet', 'Módulos', 'Módulo Estándar', 'Fabricación', 185.00),
('Closet', 'Módulos', 'Módulo con Cajonera', 'Fabricación', 225.00),
('Closet', 'Instalación', 'Instalación Closet Básico', 'Mano de Obra', 80.00),
('Closet', 'Instalación', 'Instalación Closet Premium', 'Mano de Obra', 120.00),

-- BAÑO
('Baño', 'Muebles', 'Mueble Baño 60cm 2 Puertas', 'Fabricación', 125.00),
('Baño', 'Muebles', 'Mueble Baño 80cm 2 Puertas', 'Fabricación', 145.00),
('Baño', 'Muebles', 'Mueble Baño 100cm 3 Puertas', 'Fabricación', 165.00),
('Baño', 'Muebles', 'Mueble Baño Suspendido 60cm', 'Fabricación', 135.00),
('Baño', 'Muebles', 'Mueble Baño Suspendido 80cm', 'Fabricación', 155.00),
('Baño', 'Espejos', 'Espejo 60x80cm', 'Vidriería', 45.00),
('Baño', 'Espejos', 'Espejo 80x100cm', 'Vidriería', 65.00),
('Baño', 'Espejos', 'Espejo con Marco 60x80cm', 'Vidriería', 68.00),
('Baño', 'Espejos', 'Espejo con Marco 80x100cm', 'Vidriería', 88.00),
('Baño', 'Accesorios', 'Lavamanos Sobreponer', 'Sanitarios', 85.00),
('Baño', 'Accesorios', 'Lavamanos Empotrar', 'Sanitarios', 75.00),
('Baño', 'Accesorios', 'Grifería Monocontrol', 'Sanitarios', 45.00),
('Baño', 'Accesorios', 'Organizador Bajo Lavabo', 'China', 25.00),
('Baño', 'Tableros', 'Tablero MDF Hidrófugo 18mm', 'Novopan', 32.50),
('Baño', 'Tableros', 'Canto 22mm', 'Imacasa', 0.35),
('Baño', 'Instalación', 'Instalación Mueble Baño', 'Mano de Obra', 50.00),

-- ESTANTE
('Estante', 'Tipo', 'Estante Abierto 3 Niveles', 'Fabricación', 95.00),
('Estante', 'Tipo', 'Estante Abierto 4 Niveles', 'Fabricación', 115.00),
('Estante', 'Tipo', 'Estante Abierto 5 Niveles', 'Fabricación', 135.00),
('Estante', 'Tipo', 'Estante con Puertas 3 Niveles', 'Fabricación', 145.00),
('Estante', 'Tipo', 'Estante con Puertas 4 Niveles', 'Fabricación', 175.00),
('Estante', 'Tipo', 'Estante Modular Cubo', 'Fabricación', 55.00),
('Estante', 'Accesorios', 'Soporte Invisible 30cm', 'Ferretería', 3.50),
('Estante', 'Accesorios', 'Soporte Invisible 40cm', 'Ferretería', 4.50),
('Estante', 'Accesorios', 'Bracket Metálico 25cm', 'Ferretería', 5.00),
('Estante', 'Accesorios', 'Bracket Metálico 35cm', 'Ferretería', 6.50),
('Estante', 'Tableros', 'Tablero Aglomerado 18mm', 'Imacasa', 24.76),
('Estante', 'Tableros', 'Tablero MDF 18mm', 'Novopan', 28.26),
('Estante', 'Tableros', 'Canto 22mm', 'Imacasa', 0.35),
('Estante', 'Instalación', 'Instalación Estante', 'Mano de Obra', 35.00),

-- OFICINA
('Oficina', 'Escritorios', 'Escritorio Básico 120x60cm', 'Fabricación', 145.00),
('Oficina', 'Escritorios', 'Escritorio Básico 140x70cm', 'Fabricación', 165.00),
('Oficina', 'Escritorios', 'Escritorio Ejecutivo 160x80cm', 'Fabricación', 195.00),
('Oficina', 'Escritorios', 'Escritorio en L 160x120cm', 'Fabricación', 245.00),
('Oficina', 'Cajones', 'Cajonera Móvil 3 Cajones', 'Fabricación', 95.00),
('Oficina', 'Cajones', 'Archivador 4 Cajones', 'Fabricación', 185.00),
('Oficina', 'Estantes', 'Librero 3 Niveles', 'Fabricación', 125.00),
('Oficina', 'Estantes', 'Librero 4 Niveles', 'Fabricación', 155.00),
('Oficina', 'Estantes', 'Librero 5 Niveles', 'Fabricación', 185.00),
('Oficina', 'Accesorios', 'Organizador Escritorio', 'China', 15.00),
('Oficina', 'Accesorios', 'Pasacables Metálico', 'Ferretería', 4.50),
('Oficina', 'Tableros', 'Tablero Aglomerado 18mm', 'Imacasa', 24.76),
('Oficina', 'Tableros', 'Tablero MDF 18mm', 'Novopan', 28.26),
('Oficina', 'Instalación', 'Instalación Escritorio', 'Mano de Obra', 45.00),
('Oficina', 'Instalación', 'Instalación Mueble Oficina', 'Mano de Obra', 40.00),

-- ENTRETENIMIENTO
('Entretenimiento', 'Muebles TV', 'Mueble TV 120cm Abierto', 'Fabricación', 115.00),
('Entretenimiento', 'Muebles TV', 'Mueble TV 150cm con Puertas', 'Fabricación', 145.00),
('Entretenimiento', 'Muebles TV', 'Mueble TV 180cm Modular', 'Fabricación', 185.00),
('Entretenimiento', 'Muebles TV', 'Mueble TV Suspendido 120cm', 'Fabricación', 135.00),
('Entretenimiento', 'Muebles TV', 'Mueble TV Suspendido 150cm', 'Fabricación', 165.00),
('Entretenimiento', 'Paneles', 'Panel TV con Repisas', 'Fabricación', 195.00),
('Entretenimiento', 'Paneles', 'Panel TV Completo', 'Fabricación', 245.00),
('Entretenimiento', 'Accesorios', 'Soporte TV Giratorio', 'China', 35.00),
('Entretenimiento', 'Accesorios', 'Sistema Ocultacables', 'China', 18.00),
('Entretenimiento', 'Accesorios', 'Organizador Consolas', 'China', 22.00),
('Entretenimiento', 'Tableros', 'Tablero Aglomerado 18mm', 'Imacasa', 24.76),
('Entretenimiento', 'Tableros', 'Tablero MDF 18mm', 'Novopan', 28.26),
('Entretenimiento', 'Instalación', 'Instalación Mueble TV', 'Mano de Obra', 50.00),
('Entretenimiento', 'Instalación', 'Instalación Panel TV', 'Mano de Obra', 65.00),

-- OTROS MATERIALES
('Materiales', 'Pegamento', 'Cola Blanca 1kg', 'Ferretería', 4.50),
('Materiales', 'Pegamento', 'Pegamento Contacto 1L', 'Ferretería', 12.00),
('Materiales', 'Tornillos', 'Tornillos Aglomerado x100', 'Ferretería', 3.50),
('Materiales', 'Tornillos', 'Tornillos Confirmat x100', 'Ferretería', 8.00),
('Materiales', 'Herrajes', 'Bisagra Cazoleta x100', 'China', 25.00),
('Materiales', 'Herrajes', 'Corredera Sencilla 40cm', 'China', 3.50),
('Materiales', 'Herrajes', 'Corredera Sencilla 50cm', 'China', 4.00),
('Materiales', 'Acabados', 'Laca Brillante 1L', 'Pinturas', 18.00),
('Materiales', 'Acabados', 'Laca Mate 1L', 'Pinturas', 18.00),
('Materiales', 'Acabados', 'Tinte para Madera 1L', 'Pinturas', 12.00);
